language: python

services:
  - docker

script:
  - docker build -t mcapuccini/thesparkbox .
  - bin/tsb up -d
  - sleep 60 # Give the stack 60s to get up
  - curl localhost:8080
  - curl localhost:8081
  - curl localhost:8082
  - curl localhost:8888
  - bin/tsb down

after_success:
  - >
    if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then 
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker push mcapuccini/thesparkbox
    fi
