version: "3"
services:
  master:
    image: gettyimages/spark:2.0.2-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: spark-master
    container_name: spark-master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: "spark-master.${DOMAIN:-localhost}"
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    restart: always

  worker-1:
    image: gettyimages/spark:2.0.2-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: spark-worker-1
    container_name: spark-worker-1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: "spark-worker-1.${DOMAIN:-localhost}"
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    restart: always

  worker-2:
    image: gettyimages/spark:2.0.2-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: spark-worker-2
    container_name: spark-worker-2
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: "spark-worker-2.${DOMAIN:-localhost}"
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    restart: always

  traefik:
      container_name: spark-proxy
      image: traefik:1.1.2
      ports:
        - "8080:8080"
        - "80:80"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "./traefik.toml:/etc/traefik/traefik.toml"
      restart: always
